const RequestorActionTypes = {
  REQUESTOR_WEB3: 'REQUESTOR_WEB3',
  SET_CURRENT_REQUESTOR: 'SET_CURRENT_REQUESTOR',
  IS_REQUESTOR_VERIFIED: 'IS_REQUESTOR_VERIFIED',
  SET_REQUESTOR_LOGIN_STATUS: 'SET_REQUESTOR_LOGIN_STATUS',
  CHECK_REQUESTOR_METAMASK_INSTALLED: 'CHECK_REQUESTOR_METAMASK_INSTALLED',
  CHECK_REQUESTOR_ACCOUNT_CHANGED: 'CHECK_REQUESTOR_ACCOUNT_CHANGED',
  CHECK_REQUESTOR_NETWORK_CHANGED: 'CHECK_REQUESTOR_NETWORK_CHANGED',
  CHECK_REQUESTOR_SIDEBAR_COLLAPSED: 'CHECK_REQUESTOR_SIDEBAR_COLLAPSED',
  SET_REQUESTOR_NAME: 'SET_REQUESTOR_NAME',
  REQUESTOR_LOGOUT: 'REQUESTOR_LOGOUT'
};

export default RequestorActionTypes;
