const IssuerActionTypes = {
  ISSUER_WEB3: 'ISSUER_WEB3',
  SET_CURRENT_ISSUER: 'SET_CURRENT_ISSUER',
  SET_ISSUER_LOGIN_STATUS: 'SET_ISSUER_LOGIN_STATUS',
  CHECK_ISSUER_METAMASK_INSTALLED: 'CHECK_ISSUER_METAMASK_INSTALLED',
  CHECK_ISSUER_ACCOUNT_CHANGED: 'CHECK_ISSUER_ACCOUNT_CHANGED',
  CHECK_ISSUER_NETWORK_CHANGED: 'CHECK_ISSUER_NETWORK_CHANGED',
  CHECK_ISSUER_SIDEBAR_COLLAPSED: 'CHECK_ISSUER_SIDEBAR_COLLAPSED',
  SET_ISSUER_NAME: 'SET_ISSUER_NAME',
  ISSUER_LOGOUT: 'ISSUER_LOGOUT'
};

export default IssuerActionTypes;
