const ContractActionTypes = {
  SET_INSTANCE_START: 'SET_INSTANCE_START',
  SET_INSTANCE_SUCCESS: 'SET_INSTANCE_SUCCESS',
  SET_INSTANCE_FAILURE: 'SET_INSTANCE_FAILURE',
  SET_OWNER: 'SET_OWNER',
};

export default ContractActionTypes;
