const AdminActionTypes = {
  WEB3: 'WEB3',
  SET_CURRENT_ADMIN: 'SET_CURRENT_ADMIN',
  CHECK_METAMASK_INSTALLED: 'CHECK_METAMASK_INSTALLED',
  CHECK_ACCOUNT_CHANGED: 'CHECK_ACCOUNT_CHANGED',
  CHECK_NETWORK_CHANGED: 'CHECK_NETWORK_CHANGED',
  CHECK_SIDEBAR_COLLAPSED: 'CHECK_SIDEBAR_COLLAPSED',
};

export default AdminActionTypes;
