const UserActionTypes = {
  USER_WEB3: 'USER_WEB3',
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SET_USER_LOGIN_STATUS: 'SET_USER_LOGIN_STATUS',
  CHECK_USER_METAMASK_INSTALLED: 'CHECK_USER_METAMASK_INSTALLED',
  CHECK_USER_ACCOUNT_CHANGED: 'CHECK_USER_ACCOUNT_CHANGED',
  CHECK_USER_NETWORK_CHANGED: 'CHECK_USER_NETWORK_CHANGED',
  CHECK_USER_SIDEBAR_COLLAPSED: 'CHECK_USER_SIDEBAR_COLLAPSED',
  SET_USER_NAME: 'SET_USER_NAME',
  USER_LOGOUT: 'USER_LOGOUT'
};

export default UserActionTypes;
