const UserActionTypes = {
  WEB3: 'WEB3',
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SET_CURRENT_USER_ACCOUNT: 'SET_CURRENT_USER_ACCOUNT',
  SET_CURRENT_USER_BALANCE: 'SET_CURRENT_USER_BALANCE',
  SET_CURRENT_USER_NETWORK_ID: 'SET_CURRENT_USER_NETWORK_ID',
  CHECK_METAMASK_INSTALLED: 'CHECK_METAMASK_INSTALLED',
};

export default UserActionTypes;
