const UserActionTypes = {
  WEB3: 'WEB3',
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  CHECK_METAMASK_INSTALLED: 'CHECK_METAMASK_INSTALLED',
  CHECK_ACCOUNT_CHANGED: 'CHECK_ACCOUNT_CHANGED',
  CHECK_NETWORK_CHANGED: 'CHECK_NETWORK_CHANGED',
};

export default UserActionTypes;
